### ISSUE TITLE
 invalid gradient at index 0 - expected shape [] but got [1]

### ISSUE THREAD

**Issue by debbiely77** [hbkunn/nu_gan#3]
Hi,
I want to reproduce your excellent work on my computer. When I run the nu_gan.py with --task cell_representation, I got the following errors:
Traceback (most recent call last):
  File "/home/nu_gan/nu_gan.py", line 64, in <module>
    ld, lg, lq, save_model_steps)
  File "/home/nu_gan/utils/experiment.py", line 78, in cell_representation
    dis_category=dis_category, ld=ld, lg=lg, lq=lq, save_model_steps=save_model_steps)
  File "/home/nu_gan/utils/gan_model.py", line 776, in train_representation
    errD_real.backward(mone)
  File "/home/anaconda2/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: invalid gradient at index 0 - expected shape [] but got [1]
INFO:root:Using python for large_image caching

I review the code and guess maybe it is because of the definition of mone and I tried these format:
mone = torch.Tensor([-1.0])
or
mone = torch.FloatTensor([-1.0])

Both of them don't work. 

Would you like give me some clues to solve the problem? Thank you.

**Comment by bohu615** [comment]
Hi, 

Sorry for the delay of reply.

This might due to the version conflict of pytorch. In order to run the code you need to:

1)  

Change     

>one = torch.FloatTensor([1])
>mone = one * -1

into

> one = torch.tensor(1.0)
> mone = torch.tensor(-1.0)

since pytorch starts to check if the gradient is a scalar or not.

2) 

Upsampling function 

> upsample = torch.nn.Upsample(up_size,2)

needs to be changed into

>self.upsample= torch.nn.Upsample(up_size,2)
>self.upsample = torch.nn.Upsample(scale_factor=2)

That's by far all the changes I can remember. If you use older versions it should work fine.

**Comment by bohu615** [comment]
* and also remember to swap the dimension when using initialization

I haven't tested on 1.0 version, which might bright up more problems.
